database:
  driver: mysql
  dsn: "root:root@tcp(localhost:3306)/go_exam?timeout=3s&charset=utf8&parseTime=True&loc=Local"
  keep_alive: 300
  max_opens: 20
  max_idles: 3

logging:
  mode: "debug"

server:
  http: 
    host: '0.0.0.0'
    port: '8080'
  t_server:
    host: 'localhost'
    port: '10'

grpc:
  port: "1213"